version: "3.8"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: pbproxy
    ports:
      - "8090:8090"
    environment:
      - HOST=host.docker.internal:8090
    volumes:
      - /pb_data:/root/pb_data
